
export const ASSETS_START = 'ASSETS_START'
export const ASSETS_SUCCESS = 'ASSETS_SUCCESS'
export const ASSETS_FAIL = 'ASSETS_FAIL'


export const CURRENCY_START = 'CURRENCY_START'
export const CURRENCY_SUCCESS = 'CURRENCY_SUCCESS'
export const CURRENCY_FAIL = 'CURRENCY_FAIL'
